### ISSUE TITLE
Doesn't build on node v12

### ISSUE THREAD

**Issue by T0T4R4** [olalonde/node-notify#5]
Hi mate,

It does not build on my side, do you have any idea why ?
Thanks !

``` bash
~/dev/node/github/node-notify$ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.12.0 | linux | ia32
gyp info spawn python
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/clertem/dev/node/github/node-notify/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/clertem/.node-gyp/0.12.0/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/clertem/.node-gyp/0.12.0',
gyp info spawn args   '-Dmodule_root_dir=/home/clertem/dev/node/github/node-notify',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 

~/dev/node/github/node-notify$ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.12.0 | linux | ia32
gyp info spawnmake: Entering directory `/home/clertem/dev/node/github/node-notify/build'
 make
  CXX(target) Release/obj.target/gtknotify/src/node_gtknotify.o
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
../src/node_gtknotify.cpp:101:36: error: ‘Arguments’ does not name a type
../src/node_gtknotify.cpp:101:47: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/node_gtknotify.cpp:120:41: error: ‘Arguments’ does not name a type
../src/node_gtknotify.cpp:120:52: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/node_gtknotify.cpp:146:42: error: ‘Arguments’ does not name a type
../src/node_gtknotify.cpp:146:53: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/node_gtknotify.cpp:154:77: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
../src/node_gtknotify.cpp:154:95: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
../src/node_gtknotify.cpp:160:76: error: ‘AccessorInfo’ does not name a type
../src/node_gtknotify.cpp:160:90: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
../src/node_gtknotify.cpp:166:76: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
../src/node_gtknotify.cpp:166:94: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
../src/node_gtknotify.cpp:172:75: error: ‘AccessorInfo’ does not name a type
../src/node_gtknotify.cpp:172:89: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
In file included from ../src/node_gtknotify.cpp:4:0:
/home/clertem/.node-gyp/0.12.0/deps/v8/include/v8.h: In static member function ‘static void Gtknotify::Init(v8::Handle<v8::Object>)’:
/home/clertem/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/node_gtknotify.cpp:74:23: error: within this context
../src/node_gtknotify.cpp:76:90: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
../src/node_gtknotify.cpp:76:90: note: candidate is:
In file included from ../src/node_gtknotify.cpp:4:0:
/home/clertem/.node-gyp/0.12.0/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
/home/clertem/.node-gyp/0.12.0/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../src/node_gtknotify.cpp:79:110: error: no matching function for call to ‘v8::Persistent<v8::FunctionTemplate>::New(v8::Local<v8::FunctionTemplate>&)’
../src/node_gtknotify.cpp:79:110: note: candidate is:
In file included from ../src/node_gtknotify.cpp:4:0:
/home/clertem/.node-gyp/0.12.0/deps/v8/include/v8.h:5809:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::FunctionTemplate]
/home/clertem/.node-gyp/0.12.0/deps/v8/include/v8.h:5809:4: note:   candidate expects 2 arguments, 1 provided
../src/node_gtknotify.cpp:81:46: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate>’
../src/node_gtknotify.cpp:83:46: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate>’
../src/node_gtknotify.cpp:83:61: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node_gtknotify.cpp:86:46: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate>’
../src/node_gtknotify.cpp:86:80: error: ‘New’ is not a member of ‘v8::String’
../src/node_gtknotify.cpp:87:46: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate>’
../src/node_gtknotify.cpp:87:80: error: ‘New’ is not a member of ‘v8::String’
../src/node_gtknotify.cpp:91:86: error: could not convert ‘Gtknotify::persistent_function_template’ from ‘v8::Persistent<v8::FunctionTemplate>’ to ‘v8::Handle<v8::FunctionTemplate>’
../src/node_gtknotify.cpp:92:88: error: could not convert ‘Gtknotify::persistent_function_template’ from ‘v8::Persistent<v8::FunctionTemplate>’ to ‘v8::Handle<v8::FunctionTemplate>’
../src/node_gtknotify.cpp:95:19: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node_gtknotify.cpp:95:93: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate>’
In file included from ../src/node_gtknotify.cpp:4:0:
/home/clertem/.node-gyp/0.12.0/deps/v8/include/v8.h: In static member function ‘static v8::Handle<v8::Value> Gtknotify::New(const int&)’:
/home/clertem/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/node_gtknotify.cpp:102:19: error: within this context
../src/node_gtknotify.cpp:110:37: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
../src/node_gtknotify.cpp:115:19: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
In file included from ../src/node_gtknotify.cpp:4:0:
/home/clertem/.node-gyp/0.12.0/deps/v8/include/v8.h: In static member function ‘static v8::Handle<v8::Value> Gtknotify::Send(const int&)’:
/home/clertem/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/node_gtknotify.cpp:121:23: error: within this context
../src/node_gtknotify.cpp:124:80: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
../src/node_gtknotify.cpp:127:41: error: invalid types ‘const int[int]’ for array subscript
../src/node_gtknotify.cpp:128:15: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
../src/node_gtknotify.cpp:129:21: error: invalid types ‘const int[int]’ for array subscript
../src/node_gtknotify.cpp:130:36: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
In file included from ../src/node_gtknotify.cpp:4:0:
/home/clertem/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: declared here
../src/node_gtknotify.cpp:132:27: error: invalid types ‘const int[int]’ for array subscript
../src/node_gtknotify.cpp:143:35: error: no matching function for call to ‘v8::Boolean::New(bool)’
../src/node_gtknotify.cpp:143:35: note: candidate is:
In file included from ../src/node_gtknotify.cpp:4:0:
/home/clertem/.node-gyp/0.12.0/deps/v8/include/v8.h:6194:17: note: static v8::Handle<v8::Boolean> v8::Boolean::New(v8::Isolate*, bool)
/home/clertem/.node-gyp/0.12.0/deps/v8/include/v8.h:6194:17: note:   candidate expects 2 arguments, 1 provided
/home/clertem/.node-gyp/0.12.0/deps/v8/include/v8.h: In static member function ‘static v8::Handle<v8::Value> Gtknotify::Close(const int&)’:
/home/clertem/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/node_gtknotify.cpp:147:23: error: within this context
../src/node_gtknotify.cpp:148:80: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
../src/node_gtknotify.cpp:150:28: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
In file included from ../src/node_gtknotify.cpp:4:0:
/home/clertem/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: declared here
../src/node_gtknotify.cpp: In static member function ‘static v8::Handle<v8::Value> Gtknotify::GetTitle(v8::Local<v8::String>, const int&)’:
../src/node_gtknotify.cpp:156:80: error: request for member ‘Holder’ in ‘info’, which is of non-class type ‘const int’
../src/node_gtknotify.cpp:157:14: error: ‘New’ is not a member of ‘v8::String’
../src/node_gtknotify.cpp: In static member function ‘static void Gtknotify::SetTitle(v8::Local<v8::String>, v8::Local<v8::Value>, const int&)’:
../src/node_gtknotify.cpp:161:80: error: request for member ‘Holder’ in ‘info’, which is of non-class type ‘const int’
../src/node_gtknotify.cpp: In static member function ‘static v8::Handle<v8::Value> Gtknotify::GetIcon(v8::Local<v8::String>, const int&)’:
../src/node_gtknotify.cpp:168:80: error: request for member ‘Holder’ in ‘info’, which is of non-class type ‘const int’
../src/node_gtknotify.cpp:169:14: error: ‘New’ is not a member of ‘v8::String’
../src/node_gtknotify.cpp: In static member function ‘static void Gtknotify::SetIcon(v8::Local<v8::String>, v8::Local<v8::Value>, const int&)’:
../src/node_gtknotify.cpp:173:80: error: request for member ‘Holder’ in ‘info’, which is of non-class type ‘const int’
make: *** [Release/obj.target/gtknotify/src/node_gtknotify.o] Error 1
make: Leaving directory `/home/clertem/dev/node/github/node-notify/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.2.0-4-686-pae
gyp ERR! command "node" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /home/clertem/dev/node/github/node-notify
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
```

**Comment by olalonde** [comment]
Sorry, I have no idea! Does it work with an older version of node?
